In [1]:
import numpy as np 
import pandas as pd

# Handling Missing Data

In [6]:
strdata=pd.Series(['aadvark','artichoke',np.nan,'avacado'])
strdata

0      aadvark
1    artichoke
2          NaN
3      avacado
dtype: object

In [7]:
strdata.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [11]:
strdata.fillna(value='ok') #you can also use dropna()

0      aadvark
1    artichoke
3      avacado
dtype: object

### Filtering out missing data

In [19]:
df=pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0 -0.390762  1.223004  0.435713
1 -0.531874  0.439300  1.564093
2 -0.988708  0.228080 -0.367430
3 -0.418911  0.852112  0.419516
4 -0.795514  0.184484 -1.362984
5  0.227562 -0.878597  0.271383
6 -0.322554 -0.582438  2.994271

In [24]:
from numpy import nan as na
df.iloc[:2,1:]=na
df.iloc[2:4,1]=na
df

0         1         2
0 -0.390762       NaN       NaN
1 -0.531874       NaN       NaN
2 -0.988708       NaN -0.367430
3 -0.418911       NaN  0.419516
4 -0.795514  0.184484 -1.362984
5  0.227562 -0.878597  0.271383
6 -0.322554 -0.582438  2.994271

In [26]:
df.dropna(thresh=2) #thresh: filtering based on a certain observation

0         1         2
2 -0.988708       NaN -0.367430
3 -0.418911       NaN  0.419516
4 -0.795514  0.184484 -1.362984
5  0.227562 -0.878597  0.271383
6 -0.322554 -0.582438  2.994271

### Filling the missing Data

In [29]:
df.fillna({1:0.5,2:0})  #calling fillna with the dict


0         1         2
0 -0.390762  0.500000  0.000000
1 -0.531874  0.500000  0.000000
2 -0.988708  0.500000 -0.367430
3 -0.418911  0.500000  0.419516
4 -0.795514  0.184484 -1.362984
5  0.227562 -0.878597  0.271383
6 -0.322554 -0.582438  2.994271

In [30]:
df

0         1         2
0 -0.390762       NaN       NaN
1 -0.531874       NaN       NaN
2 -0.988708       NaN -0.367430
3 -0.418911       NaN  0.419516
4 -0.795514  0.184484 -1.362984
5  0.227562 -0.878597  0.271383
6 -0.322554 -0.582438  2.994271

In [31]:
df=pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0 -1.502104  0.033025  2.318519
1 -0.528614 -0.728265 -0.783302
2  0.550764 -0.364764  0.073697
3  0.863264  1.025935 -0.710538
4  0.555675  1.101459 -0.371300
5 -2.904758 -1.127323  0.103253
6  0.166353 -0.095186 -0.553552

In [32]:
df.iloc[2:,1]=na
df.iloc[4:, 2]=na
df

0         1         2
0 -1.502104  0.033025  2.318519
1 -0.528614 -0.728265 -0.783302
2  0.550764       NaN  0.073697
3  0.863264       NaN -0.710538
4  0.555675       NaN       NaN
5 -2.904758       NaN       NaN
6  0.166353       NaN       NaN

In [33]:
df.fillna(method='ffill')

0         1         2
0 -1.502104  0.033025  2.318519
1 -0.528614 -0.728265 -0.783302
2  0.550764 -0.728265  0.073697
3  0.863264 -0.728265 -0.710538
4  0.555675 -0.728265 -0.710538
5 -2.904758 -0.728265 -0.710538
6  0.166353 -0.728265 -0.710538

In [34]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -1.502104  0.033025  2.318519
1 -0.528614 -0.728265 -0.783302
2  0.550764 -0.728265  0.073697
3  0.863264 -0.728265 -0.710538
4  0.555675       NaN -0.710538
5 -2.904758       NaN -0.710538
6  0.166353       NaN       NaN

In [35]:
df.fillna(df.mean())

0         1         2
0 -1.502104  0.033025  2.318519
1 -0.528614 -0.728265 -0.783302
2  0.550764 -0.347620  0.073697
3  0.863264 -0.347620 -0.710538
4  0.555675 -0.347620  0.224594
5 -2.904758 -0.347620  0.224594
6  0.166353 -0.347620  0.224594

# Data Transformation

### Removing duplicates

In [45]:
df=pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})
print(df.duplicated())
df.drop_duplicates()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool


k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [46]:
df['k3']=range(7)

In [47]:
df

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [50]:
df.drop_duplicates(['k1','k2'],keep='last') #By default it keeps the first one

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming data using the function

In [52]:
df=pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],'ounces':[4,3,12,6,7.4,8,3,4,5]})
df

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.4
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     4.0
8     nova lox     5.0

In [59]:
meat_to_animal={'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}


In [60]:
lowercased=df['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [61]:
df['animal']=lowercased.map(meat_to_animal)

In [62]:
df

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.4     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     4.0     pig
8     nova lox     5.0  salmon

In [63]:
df['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing values

In [64]:
data=pd.Series([1.,-999,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [65]:
data.replace(-999.0,na)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [67]:
data.replace([-999.,-1000.],na)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [69]:
data.replace([-999.,-1000.],[na,0]) #different replacement for each values

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [70]:
#the argument pass can also be a dictionary
data.replace({-999.:na,-1000.:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis indexed

In [73]:
df=pd.DataFrame(np.arange(12).reshape((3,4)),index=['tia','leh','shey'],columns=['one','two','three','four'])
df

one  two  three  four
tia     0    1      2     3
leh     4    5      6     7
shey    8    9     10    11

In [83]:
transform=lambda x: x[:4].upper()
df.index.map(transform) #doesn't have a inplace options, need to use inplace to achieve it

Index(['TIA', 'LEH', 'SHEY'], dtype='object')

In [75]:
df

one  two  three  four
tia     0    1      2     3
leh     4    5      6     7
shey    8    9     10    11

In [87]:
df.rename(index=str.title,columns=str.upper,inplace=True)
df

ONE  TWO  THREE  FOUR
Tia     0    1      2     3
Leh     4    5      6     7
Shey    8    9     10    11

In [85]:
df.rename(index={'tia':'stok'},columns={'three':'Hello'})

ONE  TWO  THREE  FOUR
Tia     0    1      2     3
Leh     4    5      6     7
Shey    8    9     10    11

### Discretization and binning

In [89]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats=pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (60.0, 100.0], (35.0, 60.0], (35.0, 60.0], (25.0, 35.0], NaN]
Length: 13
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [90]:
cats.codes

array([ 0,  0,  0,  1,  0,  0,  2,  1,  3,  2,  2,  1, -1], dtype=int8)

In [91]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [92]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [98]:
group_name=['young','young_adult','middle_aged','seniors']
pd.cut(ages,bins,labels=group_name)

['young', 'young', 'young', 'young_adult', 'young', ..., 'seniors', 'middle_aged', 'middle_aged', 'young_adult', NaN]
Length: 13
Categories (4, object): ['young' < 'young_adult' < 'middle_aged' < 'seniors']

In [100]:
data=np.random.randn(20)
data

array([ 1.73798928,  0.18507353,  0.088068  ,  0.56425327,  0.55018356,
       -0.91511711, -2.54516694,  0.95532723,  3.33228027, -0.13006706,
       -0.02664769, -0.84930422,  0.49603407,  1.70548311, -0.55453777,
       -1.86955041,  1.41440706,  1.9696774 ,  2.52239202,  1.20887649])

In [105]:
pd.cut(data,4,precision=2)

[(0.39, 1.86], (-1.08, 0.39], (-1.08, 0.39], (0.39, 1.86], (0.39, 1.86], ..., (-2.55, -1.08], (0.39, 1.86], (1.86, 3.33], (1.86, 3.33], (0.39, 1.86]]
Length: 20
Categories (4, interval[float64]): [(-2.55, -1.08] < (-1.08, 0.39] < (0.39, 1.86] < (1.86, 3.33]]

In [108]:
data=np.random.randn(1000)
cats=pd.qcut(data,4)
cats

[(0.0251, 0.705], (0.705, 2.952], (-3.5389999999999997, -0.684], (0.705, 2.952], (-3.5389999999999997, -0.684], ..., (-0.684, 0.0251], (0.705, 2.952], (0.705, 2.952], (-0.684, 0.0251], (0.705, 2.952]]
Length: 1000
Categories (4, interval[float64]): [(-3.5389999999999997, -0.684] < (-0.684, 0.0251] < (0.0251, 0.705] < (0.705, 2.952]]

In [109]:
pd.value_counts(cats)

(0.705, 2.952]                   250
(0.0251, 0.705]                  250
(-0.684, 0.0251]                 250
(-3.5389999999999997, -0.684]    250
dtype: int64

In [112]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(0.0251, 1.315], (1.315, 2.952], (-3.5389999999999997, -1.23], (0.0251, 1.315], (-3.5389999999999997, -1.23], ..., (-1.23, 0.0251], (0.0251, 1.315], (0.0251, 1.315], (-1.23, 0.0251], (0.0251, 1.315]]
Length: 1000
Categories (4, interval[float64]): [(-3.5389999999999997, -1.23] < (-1.23, 0.0251] < (0.0251, 1.315] < (1.315, 2.952]]

### Detecting and filtering out


In [16]:
df=pd.DataFrame(np.random.randn(100,4))
df.head()

0         1         2         3
0 -1.208458  1.744609 -0.054854 -0.998506
1  0.120124 -1.286035  0.076365 -0.068535
2 -1.474750 -1.016895  0.825321  1.827541
3  0.009119 -0.297310 -0.121036  1.278628
4  1.772412 -1.587941 -0.531076 -0.120303

In [19]:
col=df[2]
col[np.abs(col)>2.5]

7    -2.632459
40    2.765005
Name: 2, dtype: float64

In [26]:
df[(np.abs(df)>2.5).any(1)]

0         1         2         3
7   1.187655  0.260078 -2.632459  0.272964
40  0.353509 -1.449366  2.765005 -1.390265
57  0.050306 -0.395996 -1.046481 -2.836641

In [28]:
df[np.abs(df)>2.5]=np.sign(df)*2.5

In [32]:
df.iloc[[7,40,57]]

0         1         2         3
7   1.187655  0.260078 -2.500000  0.272964
40  0.353509 -1.449366  2.500000 -1.390265
57  0.050306 -0.395996 -1.046481 -2.500000

In [34]:
np.sign(df).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1  1.0 -1.0  1.0 -1.0
2 -1.0 -1.0  1.0  1.0
3  1.0 -1.0 -1.0  1.0
4  1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling

In [35]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [37]:
sample=np.random.permutation(5)
sample

array([3, 2, 1, 4, 0])

In [38]:
df.take(sample)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3

In [40]:
df.sample(3)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

In [41]:
choice=pd.Series([1,2,3,-4,7,6])
choice

0    1
1    2
2    3
3   -4
4    7
5    6
dtype: int64

In [43]:
choice.sample(n=10,replace=True)

0    1
0    1
5    6
1    2
5    6
5    6
5    6
1    2
4    7
4    7
dtype: int64

### Computing Indicator/ Dummy variables

In [63]:
df=pd.DataFrame({'keys':['b','a','b','c','c','a','b'],'data1':range(7)})
df

keys  data1
0    b      0
1    a      1
2    b      2
3    c      3
4    c      4
5    a      5
6    b      6

In [64]:
dummies=pd.get_dummies(df['keys'],prefix='col')
df1=df[['data1']].join(dummies)

In [66]:
df1

data1  col_a  col_b  col_c
0      0      0      1      0
1      1      1      0      0
2      2      0      1      0
3      3      0      0      1
4      4      0      0      1
5      5      1      0      0
6      6      0      1      0

# String manipulation

In [68]:
val='hello, to , my , friend'
val.split(',')

['hello', ' to ', ' my ', ' friend']

In [73]:
pieces=[x.strip() for x in val.split(',')]

In [75]:
a,b,c,d=pieces
x=a+' '+b+' '+c+' '+d
x

'hello to my friend'

In [77]:
# more generic method
y=' '.join(pieces)
y

'hello to my friend'

In [79]:
'my' in val

True

In [80]:
val.index('fr')

17

In [83]:
val.find('a')  # val.index will throw exception if the element is not found

-1

In [86]:
val.count('o')

2

In [87]:
val.replace(',','::')

'hello:: to :: my :: friend'

In [88]:
val.replace(',','')

'hello to  my  friend'

In [107]:
'1123'.ljust('154')

TypeError: 'str' object cannot be interpreted as an integer