In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [97]:
obj=pd.Series([1,2,3,4])
print(obj)

0    1
1    2
2    3
3    4
dtype: int64


In [98]:
obj2=pd.Series([4,3,5,6],index=['a','b','c','d'])
obj2

a    4
b    3
c    5
d    6
dtype: int64

In [99]:
print(obj2.values)
obj2.index

[4 3 5 6]


Index(['a', 'b', 'c', 'd'], dtype='object')

In [100]:
print(obj2[['a','b','c']])

a    4
b    3
c    5
dtype: int64


In [101]:
obj2[obj2>0]

a    4
b    3
c    5
d    6
dtype: int64

In [102]:
obj2*3

a    12
b     9
c    15
d    18
dtype: int64

In [103]:
np.exp(obj2)

a     54.598150
b     20.085537
c    148.413159
d    403.428793
dtype: float64

In [104]:
#you can also use it like a dictionary
'b' in obj2

True

In [105]:
dict1={'ohio':2,'texas':4,'oregon':6,'utah':8}
obj3=pd.Series(dict1)
obj4=pd.Series(dict1,index=['california','ohio','oregon','texas']) #index reshuffle, default is It will be same as the dictionary
obj4

california    NaN
ohio          2.0
oregon        6.0
texas         4.0
dtype: float64

In [106]:
pd.isnull(obj3) # you can also use obj3.isnull()


ohio      False
texas     False
oregon    False
utah      False
dtype: bool

In [107]:
pd.notnull(obj3)

ohio      True
texas     True
oregon    True
utah      True
dtype: bool

In [108]:
print(obj3)
obj4

ohio      2
texas     4
oregon    6
utah      8
dtype: int64


california    NaN
ohio          2.0
oregon        6.0
texas         4.0
dtype: float64

In [109]:
obj3+obj4

california     NaN
ohio           4.0
oregon        12.0
texas          8.0
utah           NaN
dtype: float64

In [110]:
obj4.name='population'
obj4.index.name='state'
obj4

state
california    NaN
ohio          2.0
oregon        6.0
texas         4.0
Name: population, dtype: float64

In [111]:
obj

0    1
1    2
2    3
3    4
dtype: int64

In [112]:
obj.index=['bob','steve','jeffu','ryan']
obj

bob      1
steve    2
jeffu    3
ryan     4
dtype: int64

# Dataframe

In [113]:
data={'state':['ohio','ohio','ohio','nevada','nevada','nevada'],'year':[2001,2002,2003,2001,2003,2002],'pop':[1.2,2.3,3.4,2.1,4.3,5.4]}
df=pd.DataFrame(data)
df.head()

state  year  pop
0    ohio  2001  1.2
1    ohio  2002  2.3
2    ohio  2003  3.4
3  nevada  2001  2.1
4  nevada  2003  4.3

In [114]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2001    ohio  1.2
1  2002    ohio  2.3
2  2003    ohio  3.4
3  2001  nevada  2.1
4  2003  nevada  4.3
5  2002  nevada  5.4

In [115]:
df2=pd.DataFrame(data,columns=['year','state','pop','try'],index=['a','b','c','d','e','f'])

In [116]:
df2.columns

Index(['year', 'state', 'pop', 'try'], dtype='object')

In [117]:
df['state']

0      ohio
1      ohio
2      ohio
3    nevada
4    nevada
5    nevada
Name: state, dtype: object

In [118]:
df.year

0    2001
1    2002
2    2003
3    2001
4    2003
5    2002
Name: year, dtype: int64

In [119]:
df2.loc['b']

year     2002
state    ohio
pop       2.3
try       NaN
Name: b, dtype: object

In [120]:
df2['try']=11.2

In [121]:
df2

year   state  pop   try
a  2001    ohio  1.2  11.2
b  2002    ohio  2.3  11.2
c  2003    ohio  3.4  11.2
d  2001  nevada  2.1  11.2
e  2003  nevada  4.3  11.2
f  2002  nevada  5.4  11.2

In [122]:
df2['try']=np.arange(6.0)

In [123]:
df2

year   state  pop  try
a  2001    ohio  1.2  0.0
b  2002    ohio  2.3  1.0
c  2003    ohio  3.4  2.0
d  2001  nevada  2.1  3.0
e  2003  nevada  4.3  4.0
f  2002  nevada  5.4  5.0

In [124]:
val=pd.Series([2.3,4.3,.2],index=['b','d','f'])
df2['try']=val
df2

year   state  pop  try
a  2001    ohio  1.2  NaN
b  2002    ohio  2.3  2.3
c  2003    ohio  3.4  NaN
d  2001  nevada  2.1  4.3
e  2003  nevada  4.3  NaN
f  2002  nevada  5.4  0.2

In [125]:
df2['bastoc']=df2.state=='ohio'
df2

year   state  pop  try  bastoc
a  2001    ohio  1.2  NaN    True
b  2002    ohio  2.3  2.3    True
c  2003    ohio  3.4  NaN    True
d  2001  nevada  2.1  4.3   False
e  2003  nevada  4.3  NaN   False
f  2002  nevada  5.4  0.2   False

In [129]:
#del df2['bastoc']
df2

year   state  pop  try
a  2001    ohio  1.2  NaN
b  2002    ohio  2.3  2.3
c  2003    ohio  3.4  NaN
d  2001  nevada  2.1  4.3
e  2003  nevada  4.3  NaN
f  2002  nevada  5.4  0.2

In [130]:
df2.columns

Index(['year', 'state', 'pop', 'try'], dtype='object')

0      ohio
1      ohio
2      ohio
3    nevada
4    nevada
5    nevada
Name: state, dtype: object

In [137]:
pop={'Nevada':{2001:2,2002:3},'ohio':{2000:23,2001:22,2002:21}}
df3=pd.DataFrame(pop)
df3

Nevada  ohio
2001     2.0    22
2002     3.0    21
2000     NaN    23

In [139]:
df3.T #Transpose of the dataframe

2001  2002  2000
Nevada   2.0   3.0   NaN
ohio    22.0  21.0  23.0

In [142]:
df4=pd.DataFrame(pop,index=[2001,2002,2003])
df4

Nevada  ohio
2001     2.0  22.0
2002     3.0  21.0
2003     NaN   NaN

In [146]:
pdata={'ohio':df4['ohio'][:-1],'Nevada':df4['Nevada'][:2]}
df5=pd.DataFrame(pdata)
df5

ohio  Nevada
2001  22.0     2.0
2002  21.0     3.0

In [149]:
df3.index.name='year'
df3.columns.name='state'
df3

state  Nevada  ohio
year               
2001      2.0    22
2002      3.0    21
2000      NaN    23

In [156]:
df2['year'].dtype

dtype('int64')

# Index object

In [2]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
print(index[:2])
index

Index(['a', 'b'], dtype='object')


Index(['a', 'b', 'c'], dtype='object')

In [3]:
#index object are immutable

In [4]:
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [5]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [6]:
obj2.index is labels

True

In [10]:
dup_labels= pd.Index(['cut','cut','bar','bar'])
dup_labels

Index(['cut', 'cut', 'bar', 'bar'], dtype='object')

In [19]:
dup_labels.append(index)

Index(['cut', 'cut', 'bar', 'bar', 'a', 'b', 'c'], dtype='object')

In [20]:
index2=pd.Index(['cut'])

In [30]:
dup_labels.unique() 

Index(['cut', 'bar'], dtype='object')

In [27]:
dup_labels 

Index(['cut', 'cut', 'bar', 'bar'], dtype='object')

# ReIndexing

In [31]:
obj1=pd.Series([1.1,4.3,2.4,3.4],index=['a','d','c','b'])
obj1

a    1.1
d    4.3
c    2.4
b    3.4
dtype: float64

In [33]:
obj2=obj1.reindex(['a','b','c','d','e'])
obj2

a    1.1
b    3.4
c    2.4
d    4.3
e    NaN
dtype: float64

In [34]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [36]:
obj3.reindex(range(6),method='ffill')  #ffill- forward fill

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [37]:
df=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','b','c'],columns=['ohio','texas','california'])
df

ohio  texas  california
a     0      1           2
b     3      4           5
c     6      7           8

In [49]:
df2=df.reindex(index=['a','b','c','d'])
df2

ohio  texas  california
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [50]:
states=['texas','utah','california']
df.reindex(columns=states)

texas  utah  california
a      1    12           2
b      4    12           5
c      7    12           8

In [47]:
df.loc[['a','b','c'],['texas','california']]

texas  california
a      1           2
b      4           5
c      7           8

# Dropping entries form an axis

In [51]:
obj=pd.Series(np.arange(5),index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [52]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [54]:
obj.drop(['b','c'])

a    0
d    3
e    4
dtype: int32

In [56]:
df=pd.DataFrame(np.arange(16).reshape(4,4),index=['leh','tia','shey','spituk'],columns=['one','two','three','four'])
df

one  two  three  four
leh       0    1      2     3
tia       4    5      6     7
shey      8    9     10    11
spituk   12   13     14    15

In [61]:
df.drop(['spituk','leh'])

one  two  three  four
tia     4    5      6     7
shey    8    9     10    11

In [62]:
df.drop('one',axis=1)

two  three  four
leh       1      2     3
tia       5      6     7
shey      9     10    11
spituk   13     14    15

In [65]:
#obj.drop(['b','c'],inplace=True)
obj

a    0
d    3
e    4
dtype: int32

# Indexing, Selection and Filtering

In [66]:
df

one  two  three  four
leh       0    1      2     3
tia       4    5      6     7
shey      8    9     10    11
spituk   12   13     14    15

In [68]:
df['one'] # Passing a single value or list selects column

leh        0
tia        4
shey       8
spituk    12
Name: one, dtype: int32

In [69]:
df[:2]

one  two  three  four
leh    0    1      2     3
tia    4    5      6     7

In [70]:
df[df['three']>5]

one  two  three  four
tia       4    5      6     7
shey      8    9     10    11
spituk   12   13     14    15

In [71]:
df>2

one    two  three  four
leh     False  False  False  True
tia      True   True   True  True
shey     True   True   True  True
spituk   True   True   True  True

In [73]:
df[df<2]=0
df

one  two  three  four
leh       0    0      2     3
tia       4    5      6     7
shey      8    9     10    11
spituk   12   13     14    15

# Selection with loc and iloc

In [74]:
df.loc['tia',['one','two']]

one    4
two    5
Name: tia, dtype: int32

In [75]:
df.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: shey, dtype: int32

In [77]:
df.iloc[2]

one       8
two       9
three    10
four     11
Name: shey, dtype: int32

In [78]:
df.iat[1,2]

6

# Integer Indexes

In [98]:
ser=pd.Series(np.arange(3.))
ser
#ser[-1] will give error

0    0.0
1    1.0
2    2.0
dtype: float64

In [95]:
ser2=pd.Series(np.arange(3),index=['a','b','c'])
print(ser2)
ser2[-2]

a    0
b    1
c    2
dtype: int32


1

In [99]:
ser[:1]

0    0.0
dtype: float64

In [101]:
ser.loc[:1] # label based indexing include end points also!

0    0.0
1    1.0
dtype: float64

In [102]:
ser.iloc[:1]

0    0.0
dtype: float64

# Arithmetic and Data Alignment

In [103]:
s1=pd.Series([7.5,3.4,5.4,1.4],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.2,4.5,5.4,2.4],index=['a','c','e','f','g'])
s1

a    7.5
c    3.4
d    5.4
e    1.4
dtype: float64

In [104]:
s2

a   -2.1
c    3.2
e    4.5
f    5.4
g    2.4
dtype: float64

In [105]:
s1+s2

a    5.4
c    6.6
d    NaN
e    5.9
f    NaN
g    NaN
dtype: float64

In [113]:
df1=pd.DataFrame(np.arange(9.).reshape(3,3),columns=list('bcd'),index=['tia','leh','shey'])
df2=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['tia','stok','leh','lea'])
df1+df2


b   c     d   e
lea   NaN NaN   NaN NaN
leh   9.0 NaN  12.0 NaN
shey  NaN NaN   NaN NaN
stok  NaN NaN   NaN NaN
tia   0.0 NaN   3.0 NaN

In [114]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})
df1+df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic method with fill values

In [116]:
df1=pd.DataFrame(np.arange(20.).reshape(4,5),columns=list('abcde'),)
df2=pd.DataFrame(np.arange(12.).reshape(3,4),columns=list('abcd'),)
df1.loc[1,'b']=np.nan

In [117]:
df1

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [118]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [119]:
1/df1

a         b         c         d         e
0       inf  1.000000  0.500000  0.333333  0.250000
1  0.200000       NaN  0.142857  0.125000  0.111111
2  0.100000  0.090909  0.083333  0.076923  0.071429
3  0.066667  0.062500  0.058824  0.055556  0.052632

In [120]:
df1.rdiv(1)

a         b         c         d         e
0       inf  1.000000  0.500000  0.333333  0.250000
1  0.200000       NaN  0.142857  0.125000  0.111111
2  0.100000  0.090909  0.083333  0.076923  0.071429
3  0.066667  0.062500  0.058824  0.055556  0.052632

#### operation beween DataFrame and Series

In [2]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [4]:
arr-arr[0] # operation is perform once for each row

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [5]:
#similarly

In [6]:
df2=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['tia','stok','leh','lea'])
df2

b     d     e
tia   0.0   1.0   2.0
stok  3.0   4.0   5.0
leh   6.0   7.0   8.0
lea   9.0  10.0  11.0

In [7]:
series=df2.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: tia, dtype: float64

In [8]:
df2-series

b    d    e
tia   0.0  0.0  0.0
stok  3.0  3.0  3.0
leh   6.0  6.0  6.0
lea   9.0  9.0  9.0

In [9]:
series2=pd.Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [11]:
df2+series2

b   d     e   f
tia   0.0 NaN   3.0 NaN
stok  3.0 NaN   6.0 NaN
leh   6.0 NaN   9.0 NaN
lea   9.0 NaN  12.0 NaN

In [12]:
series3=df2['b']
series3

tia     0.0
stok    3.0
leh     6.0
lea     9.0
Name: b, dtype: float64

In [13]:
df2.sub(series3,axis=0)

b    d    e
tia   0.0  1.0  2.0
stok  0.0  1.0  2.0
leh   0.0  1.0  2.0
lea   0.0  1.0  2.0

#### Function Application and mapping

In [8]:
df2=pd.DataFrame(np.random.randn(12).reshape(4,3),columns=list('bde'),index=['tia','stok','leh','lea'])
df2

b         d         e
tia   0.215090  0.287810  1.352399
stok -0.323960 -2.041712  0.943543
leh   0.345278 -0.734290 -1.946795
lea  -1.405248 -1.024829 -0.934988

In [9]:
df2.abs()

b         d         e
tia   0.215090  0.287810  1.352399
stok  0.323960  2.041712  0.943543
leh   0.345278  0.734290  1.946795
lea   1.405248  1.024829  0.934988

In [11]:
f=lambda x:x.max()-x.min()
df2.apply(f)

b    1.750526
d    2.329522
e    3.299194
dtype: float64

In [12]:
df2.apply(f,axis='columns')

tia     1.137309
stok    2.985255
leh     2.292073
lea     0.470260
dtype: float64

In [14]:
#It can also return series of multiple values
def f(x):
    return pd.Series([x.max(),x.min()],index=['max','min'])
df2.apply(f)

b         d         e
max  0.345278  0.287810  1.352399
min -1.405248 -2.041712 -1.946795

In [15]:
df2.apply(f,axis='columns')

max       min
tia   1.352399  0.215090
stok  0.943543 -2.041712
leh   0.345278 -1.946795
lea  -0.934988 -1.405248

In [20]:
f=lambda x:'%.2f'%x
df2.applymap(f)

b      d      e
tia    0.22   0.29   1.35
stok  -0.32  -2.04   0.94
leh    0.35  -0.73  -1.95
lea   -1.41  -1.02  -0.93

In [22]:
df2['e'].map(f) #map method apply element wise function

tia      1.35
stok     0.94
leh     -1.95
lea     -0.93
Name: e, dtype: object

### Sorting and Ranking

In [23]:
obj=pd.Series(range(4),index=['d','a','b','c'])

In [26]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [27]:
df2.sort_index()

b         d         e
lea  -1.405248 -1.024829 -0.934988
leh   0.345278 -0.734290 -1.946795
stok -0.323960 -2.041712  0.943543
tia   0.215090  0.287810  1.352399

In [29]:
df2.sort_index(axis=1)

b         d         e
tia   0.215090  0.287810  1.352399
stok -0.323960 -2.041712  0.943543
leh   0.345278 -0.734290 -1.946795
lea  -1.405248 -1.024829 -0.934988

In [30]:
df2.sort_index(axis=1,ascending=False)

e         d         b
tia   1.352399  0.287810  0.215090
stok  0.943543 -2.041712 -0.323960
leh  -1.946795 -0.734290  0.345278
lea  -0.934988 -1.024829 -1.405248

In [34]:
obj2=obj.sort_index()
obj2

a    1
b    2
c    3
d    0
dtype: int64

In [35]:
obj2.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [37]:
df2.sort_values(by='b')

b         d         e
lea  -1.405248 -1.024829 -0.934988
stok -0.323960 -2.041712  0.943543
tia   0.215090  0.287810  1.352399
leh   0.345278 -0.734290 -1.946795

In [39]:
df2.sort_values(by=['b','e'])

b         d         e
lea  -1.405248 -1.024829 -0.934988
stok -0.323960 -2.041712  0.943543
tia   0.215090  0.287810  1.352399
leh   0.345278 -0.734290 -1.946795

In [41]:
df=pd.DataFrame({'a':[2.3,2.4,2.1],'b':[6.4,3.1,2.4],'c':[5.3,2.5,1.2]})
df

a    b    c
0  2.3  6.4  5.3
1  2.4  3.1  2.5
2  2.1  2.4  1.2

In [48]:
df.rank(axis=1)

a    b    c  rank
0  2.0  4.0  3.0   1.0
1  1.0  4.0  2.0   3.0
2  3.0  4.0  2.0   1.0

In [42]:
df['rank']=df['a'].rank()

In [43]:
df

a    b    c  rank
0  2.3  6.4  5.3   2.0
1  2.4  3.1  2.5   3.0
2  2.1  2.4  1.2   1.0

In [46]:
df.sort_values(by='a')

a    b    c  rank
2  2.1  2.4  1.2   1.0
0  2.3  6.4  5.3   2.0
1  2.4  3.1  2.5   3.0

# Summarizing and Computing descriptive statistics

In [49]:
df=pd.DataFrame([[1.4,np.nan],[1.2,4.3],[np.nan,np.nan],[4.2,-3.4]],index=['a','b','c','d'],columns=['row','col'])

In [50]:
df

row  col
a  1.4  NaN
b  1.2  4.3
c  NaN  NaN
d  4.2 -3.4

In [51]:
df.sum()

row    6.8
col    0.9
dtype: float64

In [52]:
df.sum(axis=1)

a    1.4
b    5.5
c    0.0
d    0.8
dtype: float64

In [53]:
df.sum(axis=1,skipna=False)

a    NaN
b    5.5
c    NaN
d    0.8
dtype: float64

In [54]:
df.idxmax()

row    d
col    b
dtype: object

In [55]:
df.cumsum()

row  col
a  1.4  NaN
b  2.6  NaN
c  NaN  NaN
d  NaN  NaN

### Correlation and covariance

In [7]:
import pandas_datareader.data as web
all_data={ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker:data['Adj Close'] for ticker,data in all_data.items()})
volume=pd.DataFrame({ticker:data['Volume'] for ticker, data in all_data.items()})

In [9]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-02-22 -0.029799  0.015716 -0.026808 -0.017257
2021-02-23 -0.001111 -0.001241 -0.005288  0.002896
2021-02-24 -0.004052  0.020711  0.005487  0.011739
2021-02-25 -0.034783 -0.006006 -0.023705 -0.030456
2021-02-26  0.002232 -0.028905  0.014804  0.002708

In [11]:
returns['MSFT'].corr(returns['IBM'])

0.5374110605758432

In [12]:
returns['MSFT'].cov(returns['IBM'])

0.00015207789842626356

In [14]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.453430  0.708568  0.649033
IBM   0.453430  1.000000  0.537411  0.507224
MSFT  0.708568  0.537411  1.000000  0.777594
GOOG  0.649033  0.507224  0.777594  1.000000

In [15]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000358  0.000140  0.000232  0.000205
IBM   0.000140  0.000267  0.000152  0.000138
MSFT  0.000232  0.000152  0.000300  0.000224
GOOG  0.000205  0.000138  0.000224  0.000278

In [16]:
returns.corrwith(returns.IBM)

AAPL    0.453430
IBM     1.000000
MSFT    0.537411
GOOG    0.507224
dtype: float64

In [17]:
returns.corrwith(volume)

AAPL   -0.072291
IBM    -0.116868
MSFT   -0.087980
GOOG   -0.136999
dtype: float64

In [20]:
obj=pd.Series(['a','b','b','a','a','c','d','d','a',])


In [21]:
obj.unique()

array(['a', 'b', 'c', 'd'], dtype=object)

In [26]:
obj.value_counts() #similarly pd.value_counts(obj.values,sort=False)

a    4
d    2
b    2
c    1
dtype: int64

In [28]:
mask=obj.isin(['b','c'])

In [29]:
obj[mask]

1    b
2    b
5    c
dtype: object

In [2]:
to_match=pd.Series(['a','c','b','b','d','a'])
unique_values=pd.Series(['c','b','a'])
pd.Index(unique_values).get_indexer(to_match)

array([ 2,  0,  1,  1, -1,  2], dtype=int64)

In [6]:
df=pd.DataFrame({'Que1':[1,2,3,4],'Que2':[5,2,3,4],'Que3':[3,4,3,2]})
df

Que1  Que2  Que3
0     1     5     3
1     2     2     4
2     3     3     3
3     4     4     2

In [9]:
df.apply(pd.value_counts).fillna(0)

Que1  Que2  Que3
1   1.0   0.0   0.0
2   1.0   1.0   1.0
3   1.0   1.0   2.0
4   1.0   1.0   1.0
5   0.0   1.0   0.0